### ISSUE TITLE
The application does not work in big sur

### ISSUE THREAD

**Issue by gerardp** [abentele/Erbele#47] opened 2021-02-02 18:31 UTC
The application does not work in big sur

**Comment by abentele** [comment] 2021-02-02 21:06
Can you please describe what exactly doesn't work?
On which hardware? Which version of macOS?
Any crash report, screenshots or other detailed description maybe will help to reproduce the issue and fix it.

**Comment by abentele** [comment] 2021-02-02 21:08
Which version of Erbele?

**Comment by gerardp** [comment] 2021-02-03 10:14
Erbele 3.10
Mac mini (M1, 2020)
Mac Os Big Sur 11.2 (20D64)

"Erbele" is damaged and cannot be opened. You should move it to the trash.

![Captura de pantalla 2021-02-03 a las 11 11 34](https://user-images.githubusercontent.com/168353/106732381-edcbd300-6610-11eb-973f-7ac000975359.png)

**Comment by abentele** [comment] 2021-02-03 19:21
This is a duplicate of issue #46.

**Closed** 2021-02-03 19:22 UTC
