### ISSUE TITLE
Startup error and Markdown preview

### ISSUE THREAD

**Issue by lfom** [abentele/Erbele#48] opened 2021-02-22 00:57 UTC
Hello!
First, thanks a lot for Erbele, I have been using  it since a long time for personal tasks (Smultron > Fraise > Erbele). I am now using latest version (3.10) on High Sierra 10.13.6.

But only today I tried to preview a README.md (GitHub extended Markdown) and I was trilled that Erbele has support for it, but it didn't work. None of the two options worked, it just shows a blank area. Then I tried to run its binary from the terminal to see what's going on, and found out that it shows an error message on launch:

`CoreData: annotation:  Failed to load optimized model at path '/Applications/User Apps/Erbele.app/Contents/Resources/FRADataModel.momd/FRADataModel4.omo'
`

And when trying to preview Markdown:

`Can't open perl script "/Applications/User": No such file or directory`

If you need further info or testing, please let me know.

Regards

**Comment by abentele** [comment] 2021-02-22 17:16
Regarding the problem with FRADataModel: I cannot reproduce this. Maybe it has to do with High Sierra (?)
Please try to use an application path without whitespace (you use "/Applications/User Apps" with a blank - does something change if you remove the blank?

Regarding the Markdown problem: I can reproduce it. It's likely because of the blank in the path.

**Comment by lfom** [comment] 2021-02-23 00:28
Thank you for your reply. Indeed preview worked when I moved the app to my Desktop, the other error continues tho.

```
$ /Users/macuser/Desktop/Erbele.app/Contents/MacOS/Erbele   
CoreData: annotation:  Failed to load optimized model at path '/Users/macuser/Desktop/Erbele.app/Contents/Resources/FRADataModel.momd/FRADataModel4.omo'
```

**Comment by abentele** [comment] 2021-12-14 17:38
seems to be a specific problem, which cannot be reproduced with macOS Big Sur 12.0 and Erbele 4.0.1.
Therefore close this issue.

**Closed by abentele** 2021-12-14 17:38 UTC
