### ISSUE TITLE
“Erbele” is damaged and can’t be opened

### ISSUE THREAD

**Issue by jzillmann** [abentele/Erbele#49] opened 2021-03-23 10:33 UTC
On `MacOs BigSur 11.2.3` & the `Apple Silicon M1` chip.
Downloaded `Erbele 3.10`.
Can't start the app:
<img width="259" alt="Screenshot 2021-03-23 at 11 31 19" src="https://user-images.githubusercontent.com/148472/112133055-93400380-8bcb-11eb-801b-97060af84e85.png">

**Comment by abentele** [comment] 2021-03-24 06:10
This is a duplicate of issue #46. In this ticket you can find a workaround.
Sorry for the inconvenience.

**Closed by abentele** 2021-03-24 06:10 UTC

**Comment by abentele** [comment] 2021-11-14 23:25
Just released Erbele 4.0. It fixes this issue.

[![Download on the Mac App Store](./Distribution/badge-download-on-the-mac-app-store.svg)](https://apps.apple.com/de/app/erbele/id1595456360?mt=12)
