### ISSUE TITLE
Cannot save a new file from within Erbele

### ISSUE THREAD

**Issue by fbonaldi** [abentele/Erbele#57] opened 2023-05-18 19:53 UTC
When I open Erbele and then paste a text copied from somewhere else, I cannot save the text file anywhere (option CMD+S is greyed out)...

Using Ventura 13.3.1 on a IntelCore i9 MacBook Pro 16''.

Notice that, on the other hand, everything works fine on an M1 iMac.

**Comment by abentele** [comment] 2023-05-19 06:25
I cannot reproduce this (Ventura 13.3.1 / M2 Mac / Erbele 6.1.0).
I don't have a Intel based MacOS to test it.
Which version of Erbele did you use? Can you please provide the steps to reproduce this issue?

Does anybody else has this issue?

**Comment by fbonaldi** [comment] 2023-05-19 06:34
I am using 6.1, how can I download the previous one? Apple Store doesn't allow it. Maybe I should compile the source files? How to do that?

Thanks

**Comment by fbonaldi** [comment] 2023-05-19 18:07
> Hi, you may download any "pre-appstore" version from here: https://github.com/abentele/Erbele/releases (e.g. release 3.11.1)

I saw that, but the download link still leads to the App Store and then to the latest version... Is there any DMG file somewhere?

**Comment by abentele** [comment] 2023-05-19 18:11
scroll to "Erbele 3.11.1", open the "Assets", there you find a dmg file.

**Comment by fbonaldi** [comment] 2023-05-20 07:01
That's fine, I fixed it even on 6.1 (it's difficult to explain how I did, since I have all menus in Italian). Basically, I changed something in the settings – "Leave current last line" in the bottom option of the "Save & Open" tab, before there was just a blank/empty option.

**Comment by abentele** [comment] 2023-05-21 10:14
As it seems hard to reproduce this issue I propose to close it. Do you agree?

**Comment by fbonaldi** [comment] 2023-05-21 13:18
Yes.

**Closed** 2023-05-21 14:12 UTC
